### ISSUE TITLE
"wiiu-gcc-adapter-bin" wants to make changes. Enter password to allow this. + Error Opening Adapter: Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by cyndavilachase** [secretkeysio/GCAdapterDriver#12]
Getting this error message as previously described in [this other closed issue post](https://github.com/secretkeysio/GCAdapterDriver/issues/3): 

<img width="864" alt="Screen Shot 2022-11-29 at 10 14 42 PM" src="https://user-images.githubusercontent.com/119487205/204747697-d12007ed-f391-44c4-b72a-fc4d4afe30a0.png">

The error seems to come from this, which keeps popping up even if you input the password:

<img width="369" alt="Screen Shot 2022-11-29 at 9 10 18 PM" src="https://user-images.githubusercontent.com/119487205/204747781-d8a96f33-1587-4c21-a64b-637044fef0cc.png">

However, any permissions I mess with don't seem to solve the issue. Also tried renewing keychain access to it's default and tried disabling SIP to no avail. Plugged and unplugged the adapter many times and the pop-up just won't go away no matter what I try.

Any help would be appreciated. Tried posting a thread to reddit but haven't had any luck yet, so thought I'd try for the source of this driver.

**Comment by ryanmcgrath** [comment]
Mmm, `wiiu-gcc-adapter-bin` isn't anything from this repository. Where'd you get that file?

**Comment by ryanmcgrath** [comment]
Oh I see the tab in the background - that's an older driver that can't be installed alongside GCAdapterDriver. You'll want to remove/uninstall that so GCAdapterDriver is the only one.

See: https://secretkeys.io/gcadapterdriver/ in the section `How do I remove osx-wiiu-gcc-adapter?`

**Comment by cyndavilachase** [comment]
> Oh I see the tab in the background - that's an older driver that can't be installed alongside GCAdapterDriver. You'll want to remove/uninstall that so GCAdapterDriver is the only one.
> 
> See: https://secretkeys.io/gcadapterdriver/ in the section `How do I remove osx-wiiu-gcc-adapter?`

Ohhhhh. I see now! Deleting that got rid of the pop up. There's still the issue with insufficient permissions now though. I now only have this driver installed.

**Comment by ryanmcgrath** [comment]
I assume this is Catalina or Mojave, based on the window UI? Or is it Big Sur or Monterey...?

**Comment by cyndavilachase** [comment]
Monterey.

**Comment by ryanmcgrath** [comment]
After installing `GCAdapterDriver.app`, did you click the menubar icon and click the toggle?

**Comment by cyndavilachase** [comment]
Just tried that. When I click on the app icon nothing happens. Thought that meant it was just running and I didn't have to do anything else.

**Comment by ryanmcgrath** [comment]
Yup, it runs an app in the menubar of your Mac that handles loading the driver. In the future it won't be needed, theoretically, but just watch for the icon up there. You probably need to also unplug + replug in your adapter (the USB side, not the controller side) to get it to register properly.

**Comment by cyndavilachase** [comment]
Done. It's working now! Thank you so much.

**Comment by ryanmcgrath** [comment]
Congrats!
