### ISSUE TITLE
Dolphin Ishiiruka Version 3.0.3 not detecting Wii Adapter using GCAdapterDriver v1.6

### ISSUE THREAD

**Issue by evianmu** [secretkeysio/GCAdapterDriver#14]
I am currently running this on macOS Monterey version 12.5 on a Macbook Air M1 2020.

**Comment by ryanmcgrath** [comment]
What've you tried so far? This is a pretty common configuration that works.

(And what adapter type specifically?)

**Comment by evianmu** [comment]
It's the Nintendo GameCube Adapter for Wii U. I tried activating/ deactivating, unplugging / plugging, I'll try again today :( 

It was working on 3.0.2, but after the update, it stopped working. Maybe I'll try resetting my macbook. I'll keep you posted.

**Comment by evianmu** [comment]
nvm it works now 🥺
