### ISSUE TITLE
Mac keeps blocking GC Adapter Driver v.1.6

### ISSUE THREAD

**Issue by andrewsch1** [secretkeysio/GCAdapterDriver#15]
Hello, I'm using Ventura 13.1 on an M1 MacBook Pro. I seem to have a very similar issue to this person https://github.com/secretkeysio/GCAdapterDriver/issues/8. 

I am using the official Nintendo Gamecube adapter for Wii U and the latest version of Dolphin.

Every time I activate the GCAdapterDriver I have to allow it again in my system settings even though my settings allow apps downloaded from anywhere. 

When I do this, it still does not work. When I deactivate GCAdapterDriver I am prompted to enter my password. Then the same cycle occurs. 

I've tried unplugging and replugging in everything and uninstalling and reinstalling the software, as well as restarting the Mac.

GC Adapter Driver did used to work for me, several months ago, on the same 2021 M1 MacBook Pro with the same peripherals. The official adapter and controller work just fine when plugged into other devices like a Switch. 

Any ideas? Thank you.

**Comment by ryanmcgrath** [comment]
I missed this, was on vacation. Still an issue?

You should be able to keep it activated, by the way - that switch is just offering a method for loading/unloading the driver in the OS. If it's loaded but no device is plugged in, nothing should happen.
