### ISSUE TITLE
Mac won't open driver

### ISSUE THREAD

**Issue by user5732** [secretkeysio/GCAdapterDriver#16]
I'm on Mac M1 air, Ventura 13.1, and I followed the steps and tried to open the driver through the applications folder as well as in finder, but it won't run the application. I've also redownloaded it several times but it still won't work, any thoughts?

**Comment by ryanmcgrath** [comment]
You need to provide more info than just “won’t run”. What error are you seeing? If there’s no error, do you see the icon in the menubar at the top of your screen?

**Comment by user5732** [comment]
Hey thanks a ton, there was no error message and it turns out it actually was in the menubar and i managed to activate it, sorry for the inconvenience
