### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by JJMississippi1** [secretkeysio/GCAdapterDriver#19]
When I installed the GCAdapter Driver Installer, I dragged the icon to the application as it said in the instructions but when I opened it, it was the installer and not the driver. I can only get the installer but never the driver. I have a Mac Ventura

**Comment by ryanmcgrath** [comment]
Can you provide screenshots of what you're seeing? That doesn't sound... possible.

**Comment by JJMississippi1** [comment]
￼
I would drag the app into my applications and then it opens to this

**Comment by JJMississippi1** [comment]
I got the Driver activated but Dolphin still doesn't detect the adapter. Should I take the adapter out and plug it in again or should I reboot Dolphin?

**Comment by ryanmcgrath** [comment]
Dolphin or Slippi Dolphin?

And yes, you have to unplug and replug - the guide notes this.

**Comment by JJMississippi1** [comment]
Dolphin, I did that and it still didn't work. I restarted my Mac and did the same thing but nothing different.

**Comment by ryanmcgrath** [comment]
- What adapter are you using?
- If it's a Mayflash, is it in WiiU mode (there's a switch on the side of the adapter)?
- When you activated the driver, was it just via running the app, or did you also flip the toggle in the menu icon dropdown?

**Comment by JJMississippi1** [comment]
The adapter is from Syntech and there are no switches on the adapter. I flipped the toggle on the dropdown menu and it said it was activated after letting it be accepted by system preferences.

**Comment by ryanmcgrath** [comment]
Hmm, I don't know if anybody has ever tried a Syntech with this driver - frankly I've never heard of the brand.

Can you check what the hardware is identifying it as by going to:

- Apple Menu
- About This Mac
- More Info
- System Report
- USB

**Comment by JJMississippi1** [comment]
￼
Sorry it took so long, I was doing finals for college. Here’s a screenshot of what you told me to get to.

**Comment by ryanmcgrath** [comment]
If you're attaching it via Email, GitHub won't accept it - needs to be attached via the Web UI.

**Comment by JJMississippi1** [comment]
<img width="1440" alt="Screenshot 2023-05-03 at 4 21 20 PM" src="https://user-images.githubusercontent.com/132313577/236063036-c2b6db4b-afe0-4418-abf5-403ea54cb65f.png">
Does this work?

**Comment by ryanmcgrath** [comment]
Yes, though - can you click on the gamepad rather than the USB line?

**Comment by JJMississippi1** [comment]
<img width="1440" alt="Screenshot 2023-05-03 at 4 21 20 PM" src="https://user-images.githubusercontent.com/132313577/236104522-e20cbd70-924e-47cc-8bd9-fc22c3096f7c.png">
This?

**Comment by JJMississippi1** [comment]
<img width="1440" alt="Screenshot 2023-05-03 at 10 08 06 PM" src="https://user-images.githubusercontent.com/132313577/236104596-34da5d42-eb69-42a0-931a-a82bf96a9658.png">
Wrong Screenshot, sorry

**Comment by ryanmcgrath** [comment]
So that unfortunately looks like it uses an odd vendor/product ID combo, which is why the driver doesn't work.

Have you tried configuring it as a `Standard Controller` in Dolphin? That's the other way to go about this, and is fine for 99% of whatever you'd be doing - it's really mostly Melee players that might care about native response times.

**Comment by JJMississippi1** [comment]
Ok it worked, thank you
