### ISSUE TITLE
GCAdapterDriver not working over the apple one

### ISSUE THREAD

**Issue by Norcyy** [secretkeysio/GCAdapterDriver#23]
I've followed all of the instructions, i can see that both Dolphin and the computer registers my adapter, but the driver from the app doesn't seem to connect in favour of the apple one. I've done the unplug and replug, I've deleted and redownloaded, and I'm just lost on what to do, and i can't seem to find any other information on troubleshooting besides the adapter not picking up.

![Screen Shot 2024-04-05 at 7 53 04 am](https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/edd8b7d7-9111-4945-b118-3eb2ff9b970e)

also not entirely sure if i need this, as I installed via the driver app installer and it didn't include it in the instructions, but the .kext file doesn't appear in my Libray/Extensions folder. I'm not entirely sure how to grab that file from the page if i need it though

![Screen Shot 2024-04-05 at 8 12 44 am](https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/e5084a2c-e327-48b2-9c62-397c1fc78bc4)

**Comment by ryanmcgrath** [comment]
Ah, to be clear you're trying to install the `.kext`? Need to know your actual macOS version before we could even begin to debug - based on Finder I'm guessing it's 10.15 or less?

**Comment by Norcyy** [comment]
I assume that may be what i need? i’m on macOS Monterey (version 12.7.2) on a 2019 macbook air

**Comment by ryanmcgrath** [comment]
Monterey is not a `.kext`-based installation method - the GCAdapterDriver homepage indicates this:

<img width="991" alt="Screenshot 2024-04-04 at 15 52 27" src="https://github.com/secretkeysio/GCAdapterDriver/assets/22712/9bb0dd9a-452c-431d-81da-780898a77dda">

You're trying to run the `.kext` installer from the right, but you _actually_ need to do the installer on the left.

**Comment by Norcyy** [comment]
Oh yeah, I had actually used the left one. My .kext assumption was based on other comments people had left. I opened the installer, dragged it to applications, opened from my applications folder in finder. I went to system privacy to allow it to run and in my top bar it said it was activated. I was able to follow another issue up until about the halfway point when the command they ran that brought up the results in my first screenshot worked, and it showed the correct driver. Mine however, still shows the apple driver no matter how many times i unplug and replug. I should also thank you a ton for the quick response! something i definitely wasn’t expecting

**Comment by ryanmcgrath** [comment]
What's the output of `sudo systemextensionsctl list` when the driver is toggled on from the dropdown?

**Comment by Norcyy** [comment]
<img width="881" alt="Screen Shot 2024-04-05 at 9 37 40 am" src="https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/318a52c8-90c6-4319-95e4-7db0b27a8c84">

I'm currently unable to test the gc adapter itself until a few hours, this is what my list looks like. I assume it's duplicated from the times I've turned it off and on again

**Comment by ryanmcgrath** [comment]
I'd go ahead and do a full reboot to clear out any of those older installs - they _shouldn't_ be conflicting, but frankly DriverKit is weird like this and I've run into cases where people have it "just work" after a full reboot.

(DriverKit doesn't fully remove a driver install until a reboot occurs)

**Comment by Norcyy** [comment]
might be a silly question, but i assume a full reboot is just a restart? I've done this before and it didn't work, but things may have been different which i don't remember so I'll disable it and try it again

**Comment by ryanmcgrath** [comment]
A restart, yes. :)

**Comment by ryanmcgrath** [comment]
Also - what adapter type are you attempting to connect?

**Comment by Norcyy** [comment]
I'm using an official switch gamecube adapter (which i assume is the same one as the wii U)? Anyway, i restarted and now the command runs this -

<img width="573" alt="Screen Shot 2024-04-05 at 9 53 47 am" src="https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/a68dc1f4-b30a-4842-a1d6-0cbbc40385e5">

**Comment by ryanmcgrath** [comment]
Kk, and how are you connecting the adapter to your machine? Is there a particular USB hub/adapter you're using?

(And as dumb as it might sound, you're using the black cord right? _Not_ the rumble cord?)

**Comment by Norcyy** [comment]
haha, yep, it's probably important to check those. I have definitely been using the black cord the entire time, and I'm using the standard apple usb-c to usb-a adapter

<img width="307" alt="Screen Shot 2024-04-05 at 10 01 13 am" src="https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/1b763ae5-3649-4f07-b5da-aa3d2630c16a">

The adapter itself seems to connect fine, it shows up as WUP-028 in the system report, and when checking dolphin it says that there is an adapter detected. It's just that inputs won't register

**Comment by ryanmcgrath** [comment]
Screenshot your controller(s) panel from Dolphin~

**Comment by Norcyy** [comment]
ah, i currently don't have access to my controller / adapter or anything so I'm not sure anything interesting will show up but I'll post anyway and update in a few hours when i can try with the adapter connected.

<img width="670" alt="Screen Shot 2024-04-05 at 10 09 09 am" src="https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/ac526d88-2ad8-493f-abcc-95e1073b2b71">

**Comment by Norcyy** [comment]
Alright, here we go. It says that the adapter is connected, but the controller will not register anything in emulation, specifically when i try to press the start button to enter the game

![Screen Shot 2024-04-05 at 2 43 23 pm](https://github.com/secretkeysio/GCAdapterDriver/assets/166071946/b27cc1c2-1876-449c-855a-9ce6282055c4)

**Comment by ryanmcgrath** [comment]
This is plugged into port 1, correct? If it's detect, it should be outputting a Hz measurement...

**Comment by Norcyy** [comment]
is port 1 the furthest one to the back (the left one when looking straight on)? I've been using the other one, but trying it with that one doesn't seem to work either. In between testing these things do I need to reset each time? and where may the Hz measurement show up if it does work?

**Comment by ryanmcgrath** [comment]
Just set all your ports in that config panel to WiiU adapter, then each port would technically work.

Right now you only have one port enabled in the config, and the adapter says detected but not reading... which is why I ask this.

**Comment by Norcyy** [comment]
Ohh i'm understanding it now, I thought you were talking about the computer ports.

and OMG it works!!! It turns out that I had thought port 1 was the one that follows directly through the adapter cable, which is actually the last one. Thanks so much for helping, though these computer related issues do always seem to be caused by the little things that are always glossed right over. I wish you the very best!
