### ISSUE TITLE
Troubleshooting: Adapter Not Detected Sonoma

### ISSUE THREAD

**Issue by gccontrolr** [secretkeysio/GCAdapterDriver#25]
I installed the [GCAdapterDriver ](https://secretkeys.io/gcadapterdriver/) macOS 11.0+ (v1.6). I am running Sonoma on a 2023 macbook pro. So far, I have been unable to detect the gc controller in Dolphin (5.0), only my default mouse pad appears when in the "configure" setting. The hardware I am using are: game cube controller ->  an official gc controller to usb adapter -> USB to USB-C converter. Can someone please help me troubleshoot? 

<img width="599" alt="Screenshot 2024-05-21 at 1 28 03 PM" src="https://github.com/secretkeysio/GCAdapterDriver/assets/170460753/0317100b-b990-44e3-b6ab-f175e8711b08">
<img width="282" alt="Screenshot 2024-05-21 at 1 29 10 PM" src="https://github.com/secretkeysio/GCAdapterDriver/assets/170460753/001c8aa5-692f-4854-9f81-8be62c38c6e4">

**Comment by ryanmcgrath** [comment]
You're in the settings screen for the standard controller. You need to select "WiiU Controller" or whatever it is so that you get the native GC Controller protocol.

**Comment by gccontrolr** [comment]
oh my, that was it... Thank you!
