### ISSUE TITLE
Is there any version for Tiger 10.4.11 ?

### ISSUE THREAD

**Issue by lovrenco** [secretkeysio/GCAdapterDriver#4]
Would be great to have an option to run GC controller on old macs

**Comment by ryanmcgrath** [comment]
Uhhh... well, that's super old territory. Like, ancient. Are we talking Intel or PowerPC...?

I guess you could probably use the `GCAdapterDriverPassThrough` kext, as that's a _codeless_ kext and thus has no binary. Whether it successfully blocks any HID drivers that far back is anyone's guess - and to be frank I have no clue what you'd even use to play on Tiger. A system that old shouldn't need to deal with anything code signature related either - though you might need to tweak some IOKit values inside the `Info.plist` for the kext itself.

I guess just throw it in `/Library/Extensions` and try to load it? The folder back then might be different, can't remember off the top of my head.

Closing this as it's not really an issue to solve, but you're welcome to log your experience here if you think anyone else would find it useful - given the sheer age of Tiger I'm not too sure how applicable this stuff is tho.
