### ISSUE TITLE
Driver Not Downloading

### ISSUE THREAD

**Issue by addisontuohey** [secretkeysio/GCAdapterDriver#7]
Hello! I've tried downloading this driver multiple times onto my 10.14.6 Macbook Pro. I keep searching for the driver in my systems/library/extensions folder, but despite running the installer multiple times with permission granted, the driver still has not appeared in my extensions folder. Not sure what is wrong! Please help if you are able.

**Comment by ryanmcgrath** [comment]
- Did you run the installer `.pkg`?

- Are you running `sudo ls /Library/Extensions`?

**Comment by addisontuohey** [comment]
To specify, it seems like the installer is not working.

**Comment by addisontuohey** [comment]
Yup! I ran the installer and it says it's installed, but when I check the extensions folder there's unfortunately nothing there.

**Comment by addisontuohey** [comment]
<img width="432" alt="Screen Shot 2022-02-07 at 2 31 02 PM" src="https://user-images.githubusercontent.com/99215688/152867055-35d5472e-4c69-462e-975c-bc8d1da4b54f.png">
)

although it seems to maybe come up when I run sudo ls /Library/Extensions?

**Comment by addisontuohey** [comment]
Oh I have no idea what I did but it just started working!

**Comment by ryanmcgrath** [comment]
Glad it's working. :)

Drivers can be a bit funky sometimes, going to guess it was down to that. Enjoy!
